const CACHE_MAX_SIZE = 500;

const IGNORE_EMPTY_LINES = true;

const DEFAULT_GIT_ROOT_CACHE_SIZE = 100;

const CONFIG_SECTION = 'inline-blame-mini';

const DEBOUNCE_DELAY = 75;
const SAVE_DEBOUNCE_DELAY = 25;
const CHANGE_DEBOUNCE_DELAY = 150;

const GIT_TIMEOUT_MS = 5000;

const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024;
const MAX_FILE_LINES = 50000;

const PREFETCH_LINE_RADIUS = 2;

const STATUS_ICONS = {
  ERROR: '$(error)',
  WARNING: '$(warning)',
  INFO: '$(info)',
};

module.exports = {
  CACHE_MAX_SIZE,
  IGNORE_EMPTY_LINES,
  DEFAULT_GIT_ROOT_CACHE_SIZE,
  CONFIG_SECTION,
  DEBOUNCE_DELAY,
  SAVE_DEBOUNCE_DELAY,
  CHANGE_DEBOUNCE_DELAY,
  GIT_TIMEOUT_MS,
  MAX_FILE_SIZE_BYTES,
  MAX_FILE_LINES,
  PREFETCH_LINE_RADIUS,
  STATUS_ICONS,
};
